"""fix(Users): make login unique

Revision ID: 480872cf8ae4
Revises: 1b188b013cb0
Create Date: 2026-04-09 15:18:53.094688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480872cf8ae4'
down_revision: Union[str, Sequence[str], None] = '1b188b013cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_author_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['author_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_unique_constraint(None, 'users', ['login'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='unique')
    op.drop_constraint(None, 'categories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('categories_author_id_fkey'), 'categories', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###
