"""fix: add description to Category

Revision ID: 1b188b013cb0
Revises: 07b5239e2e61
Create Date: 2026-03-13 00:51:41.059776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b188b013cb0'
down_revision: Union[str, Sequence[str], None] = '07b5239e2e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
