"""update posts table

Revision ID: bfa916a2dde4
Revises: d96b017aca0e
Create Date: 2026-06-11 01:12:40.700492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa916a2dde4'
down_revision: Union[str, Sequence[str], None] = 'd96b017aca0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False))
    op.add_column('posts', sa.Column('body', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
